version: '3.8'
services:
  frontend:
    image: nginx:stable-alpine
    container_name: amc-frontend-final
    ports:
      - "3000:80"
    volumes:
      - /root/fe-abadimurnichicken/dist:/usr/share/nginx/html
    restart: always
